DROP TABLE IF EXISTS SANCTIONS;
CREATE TABLE SANCTIONS(SANCTION_ID INT AUTO_INCREMENT PRIMARY KEY, SANCTION_VALUE VARCHAR(255) NOT NULL);
INSERT INTO SANCTIONS VALUES('Nanda');
INSERT INTO SANCTIONS VALUES('Creditor123456');
INSERT INTO SANCTIONS VALUES('ABC CITY STATE ZIPCODE');
